### ISSUE TITLE
Jump box

### ISSUE THREAD

**Issue by bdmyxgh** [edevil/kubernetes-deployment#1]
The jumpbox config wont work since `ansible_ssh_common_args` is not evaluated by bootstrapped nodes.

**Comment by edevil** [comment]
It works for me so I'm going to need more information like the ansible version, the exact command used and the output when running it with the -v flag.

**Comment by bdmyxgh** [comment]
Turns out my `~/.ansible.cfg` contained extra SSH opts which prevented ssh-ing to the nodes.
Closing now.
